name: docs_pages_workflow

on:
  push:
    branches: [main]

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PATH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U sphinx
          python -m pip install furo

      - name: make the sphinx docs
        run: |
          make -C docs clean
          make -C docs html

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd docs/build/html/
          torch .nojekyll

      - name: Force push to destination branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          publish_dir: ./docs/build/html
